const char* Log(const char* message) {
	return message;
}

int multiply(int a, int b) {
	Log("Multiply");
	return a * b;
}

/*

If you've set in properties optimization then:
 - Compiler basically interprets in RUNTIME 5 * 2 as 10, hence 'return 5 * 2' is interpretted in .asm file as 'return 10'
 - It does other optimization such as discarding a function call in rutime when not used etc. But function definition is stored in asm file.

How compiler interprets functions
 - compiler interprets multiply function as 'multiply@@YAHHH@Z' and Log function as 'Log@@YAPBDPBD@Z'. The string after the function is its
   unique identification as a function. 
 - Hence when a function is called linker basically searches for the unique identification of a function from files and compiles the program
 */


 /*
 Optimization -> Disabled

; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32537.0

	TITLE	D:\Udemy\C++\2_Compiler\2_Compiler\Debug\Simple.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__AB1B5FA8_Simple@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?Log@@YAPBDPBD@Z				; Log
PUBLIC	?multiply@@YAHHH@Z				; multiply
PUBLIC	__JustMyCode_Default
PUBLIC	??_C@_08EOBDLMOI@Multiply@			; `string'
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
;	COMDAT ??_C@_08EOBDLMOI@Multiply@
CONST	SEGMENT
??_C@_08EOBDLMOI@Multiply@ DB 'Multiply', 00H		; `string'
CONST	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
;	COMDAT ?multiply@@YAHHH@Z
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
?multiply@@YAHHH@Z PROC					; multiply, COMDAT
; File D:\Udemy\C++\2_Compiler\2_Compiler\Simple.cpp
; Line 5
	push	ebp
	mov	ebp, esp
	sub	esp, 64					; 00000040H
	push	ebx
	push	esi
	push	edi
	mov	ecx, OFFSET __AB1B5FA8_Simple@cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 6
	push	OFFSET ??_C@_08EOBDLMOI@Multiply@
	call	?Log@@YAPBDPBD@Z			; Log                     -> Calling the Log function from multiply
	add	esp, 4
; Line 7
	mov	eax, DWORD PTR _a$[ebp]
	imul	eax, DWORD PTR _b$[ebp]                               -> Mutiplies the function
; Line 8
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?multiply@@YAHHH@Z ENDP					; multiply
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
;	COMDAT ?Log@@YAPBDPBD@Z
_TEXT	SEGMENT
_message$ = 8						; size = 4
?Log@@YAPBDPBD@Z PROC					; Log, COMDAT
; File D:\Udemy\C++\2_Compiler\2_Compiler\Simple.cpp
; Line 1
	push	ebp
	mov	ebp, esp
	sub	esp, 64					; 00000040H
	push	ebx
	push	esi
	push	edi
	mov	ecx, OFFSET __AB1B5FA8_Simple@cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 2
	mov	eax, DWORD PTR _message$[ebp]
; Line 3
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?Log@@YAPBDPBD@Z ENDP					; Log
_TEXT	ENDS
END

 */


// In below code after optimization we can see Log("Multiply") isn't called (i.e. call ?Log@@YAPBDPBD@Z) as it's not required

/*
Optimization -> Maximise speed

; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32537.0

	TITLE	D:\Udemy\C++\2_Compiler\2_Compiler\Debug\Simple.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__AB1B5FA8_Simple@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?Log@@YAPBDPBD@Z				; Log
PUBLIC	?multiply@@YAHHH@Z				; multiply
PUBLIC	__JustMyCode_Default
PUBLIC	??_C@_08EOBDLMOI@Multiply@			; `string'
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
;	COMDAT ??_C@_08EOBDLMOI@Multiply@
CONST	SEGMENT
??_C@_08EOBDLMOI@Multiply@ DB 'Multiply', 00H		; `string'
CONST	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?multiply@@YAHHH@Z
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
?multiply@@YAHHH@Z PROC					; multiply, COMDAT
; File D:\Udemy\C++\2_Compiler\2_Compiler\Simple.cpp
; Line 5
	push	ebp
	mov	ebp, esp
	mov	ecx, OFFSET __AB1B5FA8_Simple@cpp
	call	@__CheckForDebuggerJustMyCode@4
	push	OFFSET ??_C@_08EOBDLMOI@Multiply@
	call	?Log@@YAPBDPBD@Z			; Log
	mov	eax, DWORD PTR _a$[ebp]
	add	esp, 4
	imul	eax, DWORD PTR _b$[ebp]
; Line 8
	pop	ebp
	ret	0
?multiply@@YAHHH@Z ENDP					; multiply
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?Log@@YAPBDPBD@Z
_TEXT	SEGMENT
_message$ = 8						; size = 4
?Log@@YAPBDPBD@Z PROC					; Log, COMDAT
; File D:\Udemy\C++\2_Compiler\2_Compiler\Simple.cpp
; Line 1
	push	ebp
	mov	ebp, esp
	mov	ecx, OFFSET __AB1B5FA8_Simple@cpp
	call	@__CheckForDebuggerJustMyCode@4
	mov	eax, DWORD PTR _message$[ebp]
; Line 3
	pop	ebp
	ret	0
?Log@@YAPBDPBD@Z ENDP					; Log
_TEXT	ENDS
END

*/