; Listing generated by Microsoft (R) Optimizing Compiler Version 19.38.33130.0 

	TITLE	D:\Udemy\C++\2_Compiler\2_Compiler\Debug\Simple.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__AB1B5FA8_Simple@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?Log@@YAPBDPBD@Z				; Log
PUBLIC	?multiply@@YAHHH@Z				; multiply
PUBLIC	__JustMyCode_Default
PUBLIC	??_C@_08EOBDLMOI@Multiply@			; `string'
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
;	COMDAT ??_C@_08EOBDLMOI@Multiply@
CONST	SEGMENT
??_C@_08EOBDLMOI@Multiply@ DB 'Multiply', 00H		; `string'
CONST	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?multiply@@YAHHH@Z
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
?multiply@@YAHHH@Z PROC					; multiply, COMDAT
; File D:\Udemy\C++\2_Compiler\2_Compiler\Simple.cpp
; Line 5
	push	ebp
	mov	ebp, esp
	mov	ecx, OFFSET __AB1B5FA8_Simple@cpp
	call	@__CheckForDebuggerJustMyCode@4
	push	OFFSET ??_C@_08EOBDLMOI@Multiply@
	call	?Log@@YAPBDPBD@Z			; Log
	mov	eax, DWORD PTR _a$[ebp]
	add	esp, 4
	imul	eax, DWORD PTR _b$[ebp]
; Line 8
	pop	ebp
	ret	0
?multiply@@YAHHH@Z ENDP					; multiply
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?Log@@YAPBDPBD@Z
_TEXT	SEGMENT
_message$ = 8						; size = 4
?Log@@YAPBDPBD@Z PROC					; Log, COMDAT
; File D:\Udemy\C++\2_Compiler\2_Compiler\Simple.cpp
; Line 1
	push	ebp
	mov	ebp, esp
	mov	ecx, OFFSET __AB1B5FA8_Simple@cpp
	call	@__CheckForDebuggerJustMyCode@4
	mov	eax, DWORD PTR _message$[ebp]
; Line 3
	pop	ebp
	ret	0
?Log@@YAPBDPBD@Z ENDP					; Log
_TEXT	ENDS
END
